Name:           ros-indigo-lockfree
Version:        1.0.25
Release:        0%{?dist}
Summary:        ROS lockfree package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/lockfree
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-allocators
Requires:       ros-indigo-rosatomic
Requires:       ros-indigo-rosconsole
Requires:       ros-indigo-roslib
BuildRequires:  ros-indigo-allocators
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-rosatomic
BuildRequires:  ros-indigo-rosconsole
BuildRequires:  ros-indigo-roslib

%description
The lockfree package contains lock-free data structures for use in multithreaded
programming. These kinds of data structures are generally not as easy to use as
single-threaded equivalents, and are not always faster. If you don't know you
need to use one, try another structure with a lock around it first.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Fri Feb 06 2015 Devon Ash <dash@clearpathrobotics.com> - 1.0.25-0
- Autogenerated by Bloom

