Name:           ros-indigo-rosrt
Version:        1.0.25
Release:        0%{?dist}
Summary:        ROS rosrt package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/rosrt
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-allocators
Requires:       ros-indigo-lockfree
Requires:       ros-indigo-rosatomic
Requires:       ros-indigo-roscpp
Requires:       ros-indigo-roslib
Requires:       ros-indigo-rosunit
Requires:       ros-indigo-std-msgs
BuildRequires:  ros-indigo-allocators
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-lockfree
BuildRequires:  ros-indigo-rosatomic
BuildRequires:  ros-indigo-roscpp
BuildRequires:  ros-indigo-roslib
BuildRequires:  ros-indigo-rosunit
BuildRequires:  ros-indigo-std-msgs

%description
rosrt provides classes for interfacing with ROS from within realtime systems,
such as realtime-safe Publisher and Subscriber classes.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Fri Feb 06 2015 Devon Ash <dash@clearpathrobotics.com> - 1.0.25-0
- Autogenerated by Bloom

